### ISSUE TITLE
Error: "baseURL must end with a /", even when it does

### ISSUE THREAD

**Issue by k0d13** [amaribot/amaribot.js#1]
**Describe the bug**
Throws error when `baseURL` option ends with a slash (/).

[AmariBot.js#L21](https://github.com/amaribot-js/amaribot.js/blob/master/src/AmariBot.js#L21)
```js
if (options.baseURL !== undefined && options.baseURL.endsWith("/")) throw new Error("baseURL must end with a /")
```
I'm assuming should be changed to
```js
if (options.baseURL !== undefined && !options.baseURL.endsWith("/")) throw new Error("baseURL must end with a /")
```

**To Reproduce**     
1. `new AmariBot("AMARIBOTAPITOKEN", { baseURL: "https://amaribot.com/api/" })`

**Expected behavior**   
No error.

**Versions**     
* Node.js: v16.6.1
* NPM: v7.20.3
* AmariBot.js: v1.0.1

**Additional context**
Unrelated to this but the leaderboard and rewards examples don't work.
Its reassigning the AmariBot constant in both examples:
`SyntaxError: Identifier 'AmariBot' has already been declared`
and the in the rewards example something similar is happening:
`SyntaxError: Identifier 'level' has already been declared`.
Also in the rewards example `message` is not declared, but I don't
know if that example is meant to be in a message event.

**Comment by thewilloftheshadow** [comment]
I'm an idiot for that 😂😂 

As far as the tutorials go, yea they aren't really tested or anything, I just wrote random junk at 4an and it looked like it worked to me. I'll probably remove them
