### ISSUE TITLE
Make it so when calling the function guildID and userID don't have to be Strings

### ISSUE THREAD

**Issue by Wiggle37** [amaribot/amaribot.js#4]
Make it so when calling the function guildID and userID don't have to be Strings

**Comment by thewilloftheshadow** [comment]
What would be the use case for this? When you get them from Discord they’re always strings, and when I send them to the API they need to be strings… I don’t mind the change but there needs to be a reason

**Comment by thewilloftheshadow** [comment]
What would be the use case for this? When you get them from Discord they’re always strings, and when I send them to the API they need to be strings… I don’t mind the change but there needs to be a reason

**Comment by Wiggle37** [comment]
Ahhh, ok. I was wondering if there was a reason for them being strings, I felt that it was weird because it is technically an integer but you made us put them in as strings
