### ISSUE TITLE
Queue System

### ISSUE THREAD

**Issue by thewilloftheshadow** [amaribot/amaribot.js#5]
# Queue System
This system will automatically queue requests that you make when you are ratelimited

- [x] Automatically queue requests
- [ ] Disable queue in constructor
- [ ] Cancel requests in the queue

**Comment by BrianWasTaken** [comment]
I suggest using [Sapphire's AsyncQueue](https://www.npmjs.com/package/@sapphire/async-queue) for this since discord.js uses the same.

**Comment by thewilloftheshadow** [comment]
Ooo that's exactly what I was looking for, thanks!
